# Generated by Django 5.0.2 on 2024-02-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_society_building_building_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_building',
            name='building_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('commercial ', 'commercial ')], default='commercial', max_length=50),
        ),
    ]
