# Generated by Django 5.0.2 on 2024-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_society_building_building_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_building',
            name='building_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial ', 'Commercial ')], default='Commercial', max_length=50),
        ),
    ]
