# Generated by Django 5.0.2 on 2024-02-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_society_building_building_type'),
        ('utility', '0008_remove_locality_description_remove_locality_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_building',
            name='google_map',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='BuilderDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('google_map', models.CharField(blank=True, max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
            ],
            options={
                'verbose_name_plural': '3. BuilderDeveloper',
            },
        ),
        migrations.AddField(
            model_name='society_building',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.builderdeveloper'),
        ),
    ]
