# Generated by Django 5.0.2 on 2024-02-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name_plural': '8. Key_Words'},
        ),
    ]
