# Generated by Django 5.0.2 on 2024-02-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_country_alter_approx_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='state',
        ),
    ]
