# Generated by Django 5.0.2 on 2024-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_rename_country_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='level',
        ),
        migrations.RemoveField(
            model_name='city',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='city',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='city',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='city',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='level',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
