# Generated by Django 5.0.2 on 2024-02-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_remove_city_level_remove_city_lft_remove_city_parent_and_more'),
        ('vendor', '0005_delete_dealin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyWords',
        ),
    ]
