# Generated by Django 5.0.2 on 2024-02-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_delete_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='description',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='status',
        ),
        migrations.AlterField(
            model_name='locality',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
